name: Create BookStack Article

on:
  issues:
    types: [opened, edited, closed]

jobs:
  bookstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install marked node-fetch

      - name: Create/Update BookStack Page
        env:
          BOOKSTACK_URL: ${{ secrets.BOOKSTACK_URL }}
          BOOKSTACK_API_TOKEN: ${{ secrets.BOOKSTACK_API_TOKEN }}
          BOOKSTACK_API_EMAIL: ${{ secrets.BOOKSTACK_API_EMAIL }}
        run: |
          node scripts/bookstack.js
